"""Prometheus metrics.

Metric objects are process-global (the prometheus_client convention) and
are updated at their actual call sites in the upload service and worker
pipeline - not decoratively. queue_length is the one exception: nothing in
the process naturally tracks queue depth between scrapes, so it's computed
on demand at scrape time via a Redis LLEN on ARQ's queue key (see
GET /metrics in app.main).
"""

from prometheus_client import Counter, Gauge, Histogram

upload_duration_seconds = Histogram(
    "cmip_upload_duration_seconds", "Time spent handling a document upload request"
)
ocr_duration_seconds = Histogram(
    "cmip_ocr_duration_seconds", "Time spent running OCR on a single page or image"
)
extraction_duration_seconds = Histogram(
    "cmip_extraction_duration_seconds", "Time spent on text/table extraction for one document"
)
processing_duration_seconds = Histogram(
    "cmip_processing_duration_seconds", "End-to-end duration of a document ingestion job"
)
documents_processed_total = Counter(
    "cmip_documents_processed_total", "Documents that finished a processing job", ["status"]
)
worker_failures_total = Counter(
    "cmip_worker_failures_total", "Processing job failures (including ones that will retry)",
    ["job_type"],
)
job_retries_total = Counter(
    "cmip_job_retries_total", "Processing job retry attempts", ["job_type"]
)
queue_length = Gauge(
    "cmip_queue_length", "Jobs currently queued in the ARQ ingestion queue"
)

# NOTE: the 5 "AI engine / LLM providers" metrics that used to live here
# (Phase 3.1) moved to ai_service.observability.metrics in Pre-Phase 5 (AI
# Service Extraction) - they're AI-specific, not general backend metrics,
# and prometheus_client raises on a duplicate metric name so they could
# never be declared in both places. GET /metrics in app.main is unaffected:
# it reads the process-global default registry, which both modules
# register into regardless of which one defines a given metric. The
# embedding-call/rerank metrics Phase 5 adds follow the same split and
# live in ai_service.observability.metrics, not here - only the retrieval-
# orchestration metrics below (BM25/vector/graph-expansion timing, the
# things HybridRetriever itself does) are backend-owned.

# --- Retrieval (Phase 5: Knowledge Retrieval Platform) ---

bm25_search_duration_seconds = Histogram(
    "cmip_bm25_search_duration_seconds", "Time spent in one BM25Search.search() call"
)
vector_search_duration_seconds = Histogram(
    "cmip_vector_search_duration_seconds", "Time spent in one VectorSearch.search() call"
)
graph_expansion_duration_seconds = Histogram(
    "cmip_graph_expansion_duration_seconds", "Time spent in one GraphExpansion.expand() call"
)
retrieval_run_duration_seconds = Histogram(
    "cmip_retrieval_run_duration_seconds", "End-to-end duration of one HybridRetriever run"
)
retrieval_context_size = Histogram(
    "cmip_retrieval_context_size", "Total items (chunks+nodes+edges+...) in one RetrievalContext"
)
embeddings_generated_total = Counter(
    "cmip_embeddings_generated_total",
    "Embeddings actually (re)generated by generate_embeddings_task (excludes hash-guarded skips)",
    ["source_type"],
)

# Recall/precision are deliberately Gauges, not computed automatically:
# they require labeled relevance judgments that don't exist online (see
# app.modules.retrieval.evaluation_service's module docstring) - a future
# offline evaluation job sets these from EvaluationService.compute_metrics,
# they are never set from unlabeled retrieval results.
retrieval_recall_at_k = Gauge(
    "cmip_retrieval_recall_at_k", "Offline-evaluated recall@K, set by a future evaluation job"
)
retrieval_precision_at_k = Gauge(
    "cmip_retrieval_precision_at_k", "Offline-evaluated precision@K, set by a future evaluation job"
)
